In [ ]:
#https://qiita.com/rindai87/items/4b6f985c0583772a2e21

# 定数 constant

In [1]:
# （定数）+（定数）の足し算
import tensorflow as tf

# 入力となる定数の定義
x = tf.constant(1, name="x")
y = tf.constant(2, name="y")

add_op = tf.add(x, y)

with tf.Session() as sess:
    print(sess.run(add_op))

3


# 変数 Variable

In [2]:
import tensorflow as tf

# cntという変数（カウンター）の定義
cnt = tf.Variable(0, name="cnt")
inc = tf.constant(1, name="inc")

# カウントアップ
add_op = tf.add(cnt, inc)

# cntの値を更新
up_op = tf.assign(cnt, add_op)

with tf.Session() as sess:
    # 変数を使う場合はまず初期化が必要
    sess.run(tf.global_variables_initializer())

    # カウントアップを計3回実行
    print(sess.run(up_op))
    print(sess.run(up_op))
    print(sess.run(up_op))

1
2
3


# placeholder

In [3]:
import tensorflow as tf

# 定数の定義
x = tf.constant(1, name="x")
# プレースホルダーという箱を用意する
y = tf.placeholder(tf.int32, name="y")

# x+yの演算を定義
add_op = tf.add(x, y)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    # プレースホルダーには、feed_dictという仕組みを通じて値を外挿できる
    print(sess.run(add_op, feed_dict={y:1}))
    print(sess.run(add_op, feed_dict={y:3}))

2
4


# Session

In [4]:
import tensorflow as tf

cnt = tf.Variable(0, name="cnt")
inc = tf.constant(1, name="inc")

add_op = tf.add(cnt, inc)
up_op = tf.assign(cnt, add_op)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(up_op))
    print(sess.run(up_op))
    print(sess.run(up_op))


with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(up_op))
    print(sess.run(up_op))
    print(sess.run(up_op))

1
2
3
1
2
3


# Tensor

In [5]:
import  tensorflow as tf

# ランク2のテンソル（行列）の定義
x = tf.constant([[1,2], [1,2]], tf.int32, name="x")
y = tf.constant([[3,4], [3,4]], tf.int32, name="y")

# 行列の足し算
add_op = tf.add(x, y)

with tf.Session() as sess:
    print(sess.run(x))
    print(sess.run(y))
    print(sess.run(add_op))


[[1 2]
 [1 2]]
[[3 4]
 [3 4]]
[[4 6]
 [4 6]]
